blog/urls.py
# coding: utf-8
from __future__ import unicode_literals, absolute_import
from django.conf.urls import patterns, url
from .views import BlogListView, BlogDetailView

urlpatterns = patterns('',
                       url(r'^$', BlogListView.as_view(), name='list'),
                       url(r'^(?P<slug>[-\w]+)/$', BlogDetailView.as_view(), name='detail'))

core/urls.py
# coding: utf-8
from __future__ import unicode_literals, absolute_import
from core.views import HomeTemplateView, CrossDomainTemplateView, RobotsTemplateView, HumansTemplateView, ContactView, ProfileDetailView
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^$', HomeTemplateView.as_view(), name='home'),
    url(r'^contato/$',  ContactView.as_view(), name='contact'),

    # User e Profile
    url(r'^autenticar/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^autenticado/$', 'core.views.logged_in', name='logged_in'),
    url(r'^sair/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),
    url(r'^cadastro/$', 'core.views.register', name='register'),
    url(r'^cadastro/editar/$', 'core.views.register_update', name='register_update'),
    url(r'^senha/alterar/$', 'django.contrib.auth.views.password_change', {'post_change_redirect': '/'}, name='password_change'),

    # Redefinir senha
    url(r'^password_reset/$', 'django.contrib.auth.views.password_reset', name='password_reset'),
    url(r'^password_reset/done/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
    url(r'^reset/(?P<uidb36>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'django.contrib.auth.views.password_reset_confirm',
        name='password_reset_confirm'),
    url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete', name='password_reset_complete'),

    # SEO
    url(r'^robots\.txt$', RobotsTemplateView.as_view(), name='robots'),
    url(r'^humans\.txt$', HumansTemplateView.as_view(), name='robots'),
    url(r'^crossdomain\.xml$', CrossDomainTemplateView.as_view(), name='crossdomain'),

    # A ultima url deve ser a do profile
    url(r'^(?P<slug>[-\w]+)/$', ProfileDetailView.as_view(), name="profile_detail"),
)

xsdes/urls.py
from core.views import ProfileDetailView
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls', namespace='blog')),

    # A ultima url deve ser a do core
    url(r'^', include('core.urls', namespace='core')),
)

core/models.py
# coding: utf-8
from __future__ import unicode_literals, absolute_import
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify


class Profile(models.Model):
    user = models.OneToOneField(User)
    slug = models.SlugField(max_length=100, unique=True, editable=False)
    site = models.URLField(blank=True, null=True)
    twitter = models.CharField(max_length=100, blank=True, null=True)
    facebook = models.CharField(max_length=100, blank=True, null=True)
    linkedin = models.CharField(max_length=100, blank=True, null=True)
    github = models.URLField(blank=True, null=True)
    bitbucket = models.URLField(blank=True, null=True)
    cv = models.TextField(blank=True, null=True)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.pk:
            self.slug = slugify(self.user.username)
        super(Profile, self).save(force_insert, force_update, using)

    class Meta:
        verbose_name = 'Perfil'
        verbose_name_plural = 'Perfis'

    def get_absolute_url(self):
        return '/%s/' % self.slug

    def __unicode__(self):
        return self.user.username

core/forms.py
# coding: utf-8
from __future__ import unicode_literals, absolute_import
import re
from django import forms
from django.utils.translation import ugettext as _
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django.forms.fields import Field
from django.core.validators import EMPTY_VALUES
from django.forms import ValidationError
from .models import Profile

try:
    from django.utils.encoding import smart_text
except ImportError:
    from django.utils.encoding import smart_unicode as smart_text

phone_digits_re = re.compile(r'^(\d{2})[-\.]?(\d{4,5})[-\.]?(\d{4})$')


class BRPhoneNumberField(Field):
    default_error_messages = {
        'invalid': _(u'Os números de telefone deve estar em um dos seguintes '
                     'formatos: 99-9999-9999 ou 99-99999-9999, pode ser escrito sem os hífens.'),
    }

    def clean(self, value):
        super(BRPhoneNumberField, self).clean(value)
        if value in EMPTY_VALUES:
            return ''
        value = re.sub('(\(|\)|\s+)', '', smart_text(value))
        m = phone_digits_re.search(value)
        if m:
            return '%s-%s-%s' % (m.group(1), m.group(2), m.group(3))
        raise ValidationError(self.error_messages['invalid'])


class ContactForm(forms.Form):
    name = forms.CharField(label=_('Nome'), required=True)
    email = forms.EmailField(label=_('Email'), required=True)
    phone = BRPhoneNumberField(label=_('Telefone'), required=True)
    subject = forms.CharField(label=_('Assunto'), required=True)
    message = forms.CharField(label=_('Mensagem'), widget=forms.Textarea, required=True)


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ('user',)


class UserForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields.keyOrder = ['username', 'password1', 'password2', 'first_name', 'last_name', 'email']

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')


class UserUpdateForm(UserChangeForm):
    def __init__(self, *args, **kwargs):
        super(UserUpdateForm, self).__init__(*args, **kwargs)
        self.fields.keyOrder = ['username', 'first_name', 'last_name', 'email']

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

core/views.py
# coding: utf-8
from __future__ import unicode_literals, absolute_import
from django.conf import settings
from django.contrib import messages
from django.core.mail.message import EmailMessage
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.template.loader import render_to_string
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormView
from django.utils.translation import ugettext as _
from django.shortcuts import redirect, render_to_response, get_object_or_404
from django.template import RequestContext
from django.contrib.auth.models import User
from .forms import ContactForm
from .models import Profile
from .forms import ProfileForm, UserForm, UserUpdateForm


class HomeTemplateView(TemplateView):
    template_name = 'base.html'


def logged_in(request):
    return redirect(request.user.get_profile().get_absolute_url())


def register(request):
    userform = UserForm(request.POST or None)
    userprofileform = ProfileForm(request.POST or None)

    if userform.is_valid() and userprofileform.is_valid():
        user = userform.save()
        userprofile = userprofileform.save(commit=False)
        userprofile.user = user
        userprofile.save()
        return redirect(userprofile.get_absolute_url())

    return render_to_response(
        'core/register.html',
        dict(userform=userform, userprofileform=userprofileform),
        context_instance=RequestContext(request),
    )


def register_update(request):
    user = get_object_or_404(User, pk=request.user.pk)

    if request.method == 'POST':
        userform = UserUpdateForm(request.POST, instance=user)
        userprofileform = ProfileForm(request.POST, instance=user.get_profile())

        if userform.is_valid() and userprofileform.is_valid():
            user = userform.save()
            userprofile = userprofileform.save(commit=False)
            userprofile.user = user
            userprofile.save()
            return redirect(userprofile.get_absolute_url())

    else:
        userform = UserUpdateForm(instance=user)
        userprofileform = ProfileForm(instance=user.get_profile())

    return render_to_response(
        'core/register.html',
        dict(userform=userform, userprofileform=userprofileform),
        context_instance=RequestContext(request),
    )


class ProfileDetailView(DetailView):
    model = Profile


class ContactView(FormView):
    template_name = 'core/contact.html'
    form_class = ContactForm

    def get_success_url(self):
        return reverse_lazy('core:contact')

    def form_invalid(self, form):
        messages.add_message(self.request, messages.ERROR,
                             _(u'O formulário está inválido. Todos os campos são requeridos.'))
        return self.render_to_response(self.get_context_data(form=form))

    def form_valid(self, form):
        """
        This method is called when valid form data has been POSTed.
        It should return an HttpResponse.
        """

        name = form.cleaned_data['name']
        email = form.cleaned_data['email']
        phone = form.cleaned_data['phone']
        subject = form.cleaned_data['subject']
        message_part = form.cleaned_data['message']
        message = render_to_string(
            'snippets/email.html', {
                'name': name,
                'email': email,
                'phone': phone,
                'subject': subject,
                'message': message_part,
            }
        )

        msg = EmailMessage(subject=subject, body=message, from_email=email, to=[settings.DEFAULT_TO_EMAIL])
        msg.content_subtype = 'html'

        try:
            msg.send()
            messages.add_message(self.request, messages.SUCCESS, _('Mensagem enviada com sucesso!'))
        except Exception, e:
            messages.add_message(self.request, messages.ERROR, e)

        return HttpResponseRedirect(reverse_lazy('core:contact'))


class RobotsTemplateView(TemplateView):
    template_name = 'robots.txt'

    def render_to_response(self, context, **response_kwargs):
        return self.response_class(
            request=self.request,
            template=self.get_template_names(),
            context=context,
            mimetype='test/plain',
            **response_kwargs
        )


class HumansTemplateView(TemplateView):
    template_name = 'humans.txt'

    def render_to_response(self, context, **response_kwargs):
        return self.response_class(
            request=self.request,
            template=self.get_template_names(),
            context=context,
            mimetype='test/plain',
            **response_kwargs
        )


class CrossDomainTemplateView(TemplateView):
    template_name = 'crossdomain.xml'

    def render_to_response(self, context, **response_kwargs):
        return self.response_class(
            request=self.request,
            template=self.get_template_names(),
            context=context,
            mimetype='application/xml',
            **response_kwargs
        )

templates/core/contact.html
{% extends "base.html" %}
{% load i18n bootstrap_toolkit %}

{% block content %}
    <div class="row">
        <div class="span12">
            <form class="form-horizontal" method="post">
                <h3 class="page-header">{% trans 'Contato' %}</h3>
                {% csrf_token %}
                {{ form|as_bootstrap }}
                <div class="form-actions">
                    <input type="submit" value="Enviar" class="btn btn-primary">
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script>
        $("#contact").addClass("active");
        $("#id_name").focus();
    </script>
{% endblock %}

templates/core/profile_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load gravatar %}

{% block title %}
- {{ profile.user.username|capfirst }}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="span2">
            <p><a href="{{ profile.site }}" target="_blank"><img class="img-polaroid" src="{% gravatar_url profile.user.email 160 %}" alt="{{ profile.user.username }}" width="160" height="160" /></a></p>
            <p><i class="icon-share"></i> <strong>Redes sociais</strong></p>
            <ul class="redes-sociais">
                {% if profile.twitter %}
                    <li><a href="http://twitter.com/{{ profile.twitter }}">@{{ profile.twitter }}</a></li>
                {% endif %}
                {% if profile.facebook %}
                    <li><a href="{{ profile.facebook }}">Facebook</a></li>
                {% endif %}
                {% if profile.linkedin %}
                    <li><a href="{{ profile.linkedin }}">LinkedIn</a></li>
                {% endif %}
                {% if profile.bitbucket %}
                    <li><a href="{{ profile.bitbucket }}">Bitbucket</a></li>
                {% endif %}
                {% if profile.github %}
                    <li><a href="{{ profile.github }}">Github</a></li>
                {% endif %}
            </ul>
        </div>
        <div class="span6">
            <h3 class="page-header">
                {% if profile.site %}
                    <a href="{{ profile.site }}">
                {% endif %}

                {% if profile.user.first_name and profile.user.last_name %}
                    {{ profile.user.first_name }} {{ profile.user.last_name }}
                {% elif profile.user.first_name %}
                    {{ profile.user.first_name }}
                {% else %}
                    {{ profile.user.username|capfirst }}
                {% endif %}

                {% if profile.site %}
                <small>
                    {% if profile.site|slice:":5" == 'https' %}
                        {{ profile.site|slice:"8:" }}
                    {% else %}
                        {{ profile.site|slice:"7:" }}
                    {% endif %}
                </small></a>
                {% endif %}
            </h3>
            {% if profile.cv %}
                <h3>{% trans 'Mini CV' %}</h3>
                {% autoescape off %}{{ profile.cv }}{% endautoescape %}
            {% endif %}
        </div>
        <div class="span4">
            {% include "blog/blogroll.html" %}
        </div>
    </div>
{% endblock %}

{% block script %}
    <script>
        $("#profile_detail").addClass("active");
    </script>
{% endblock %}

templates/core/register.html
{% extends "base.html" %}
{% load i18n bootstrap_toolkit staticfiles %}

{% block title %}Registro{% endblock %}

{% block content %}
<div class="row">
    <form class="form-horizontal" method="post">{% csrf_token %}
        <div class="span6">
            <h3 class="page-header">{% trans 'Usuário' %}</h3>
            {{ userform|as_bootstrap }}
            <h3 class="page-header">{% trans 'Perfil' %}</h3>
            {{ userprofileform|as_bootstrap }}
        </div>
        <div class="span6">
            <h3 class="page-header">{% trans 'Mini CV' %}</h3>
            <textarea id="redactor"></textarea>
        </div>
        <div class="span12">
            <div class="form-actions">
                <input type="submit" value="{% trans 'Save' %}" class="btn btn-primary" id="salvar">
            </div>
        </div>
    </form>
</div>
{% endblock %}

{% block extra_head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/redactor.css' %}" rel="stylesheet">
{% endblock %}
{% block script %}
    <script src="{% static 'js/redactor.js' %}"></script>
    <script>
        $(".register").addClass("active");
        $("#id_username").focus();
        
        // Redactor
        $(function(){
            $('#redactor').redactor();
            
            // Pegar texto para visualização
            var $id_cv = $("#id_cv");
            var text_content = $id_cv.text();
            $(".redactor_editor").html(text_content);
            
            // Enviar texto
            $("#salvar").click(function(){
                var html_content = $(".redactor_editor").html();
                $("#id_cv").html(html_content);
            });

            // Escondendo elemento textarea de CV
            $id_cv.closest(".control-group").css({"overflow": "hidden", "height": "0"});
        });
    </script>
{% endblock %}