blog/urls.py
# coding: utf-8
from __future__ import unicode_literals, absolute_import
from django.conf.urls import patterns, url
from .views import BlogListView, BlogDetailView

urlpatterns = patterns('',
                       url(r'^$', BlogListView.as_view(), name='list'),
                       url(r'^(?P<slug>[-\w]+)/$', BlogDetailView.as_view(), name='detail'))

core/urls.py
# coding: utf-8
from __future__ import unicode_literals, absolute_import
from core.views import HomeTemplateView, CrossDomainTemplateView, RobotsTemplateView, HumansTemplateView, ContactView, ProfileDetailView
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^$', HomeTemplateView.as_view(), name='home'),
    url(r'^contato/$',  ContactView.as_view(), name='contact'),

    # User e Profile
    url(r'^autenticar/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^autenticado/$', 'core.views.logged_in', name='logged_in'),
    url(r'^sair/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),
    url(r'^cadastro/$', 'core.views.register', name='register'),
    url(r'^cadastro/editar/$', 'core.views.register_update', name='register_update'),
    url(r'^senha/alterar/$', 'django.contrib.auth.views.password_change', {'post_change_redirect': '/'}, name='password_change'),

    # Redefinir senha
    url(r'^password_reset/$', 'django.contrib.auth.views.password_reset', name='password_reset'),
    url(r'^password_reset/done/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
    url(r'^reset/(?P<uidb36>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'django.contrib.auth.views.password_reset_confirm',
        name='password_reset_confirm'),
    url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete', name='password_reset_complete'),

    # SEO
    url(r'^robots\.txt$', RobotsTemplateView.as_view(), name='robots'),
    url(r'^humans\.txt$', HumansTemplateView.as_view(), name='robots'),
    url(r'^crossdomain\.xml$', CrossDomainTemplateView.as_view(), name='crossdomain'),

    # A ultima url deve ser a do profile
    url(r'^(?P<slug>[-\w]+)/$', ProfileDetailView.as_view(), name="profile_detail"),
)

xsdes/urls.py
from core.views import ProfileDetailView
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls', namespace='blog')),

    # A ultima url deve ser a do core
    url(r'^', include('core.urls', namespace='core')),
)

templates/base.html
{% load i18n staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% trans 'XSD' %} {% block title %}{% trans 'Extreme Software & Design' %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% trans 'Empresa prestadora de consultoria e desenvolvimento de soluções para sites ou sistemas baseados em tecnologias web com especialidade em HTML5, CSS3, JavaScript, jQuery, Python e django framework, que também projeta, desenvolve e implementa soluções em design gráfico e de experiência do usuário com a interface gráfica com foco em cognitividade, usabilidade e acessibilidade em conformidade com os padrões e semanticas aplicadas a web.' %}">
    <meta name="author" content="Mário Chaves">
    <meta name="reply-to" content="macndesign@gmail.com">
    <meta name="keywords" content="sites, web, desenvolvimento, development, html, design, sistemas, softwares,">

    <!-- Le humans -->
    <link type="text/plain" rel="author" href="http://www.xsd.com.br/humans.txt">

    <!-- Le styles -->
    <link href='http://fonts.googleapis.com/css?family=Days+One|Open+Sans:400,700' rel='stylesheet' type='text/css'>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-responsive.css' %}" rel="stylesheet">
    <link href="{% static 'css/pygments_default.css' %}" rel="stylesheet">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="{% static 'ico/favicon.ico' %}">
    <link rel="apple-touch-icon-precomposed" sizes="144x144"
          href="{% static 'ico/apple-touch-icon-144-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="114x114"
          href="{% static 'ico/apple-touch-icon-114-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="72x72"
          href="{% static 'ico/apple-touch-icon-72-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" href="{% static 'ico/apple-touch-icon-57-precomposed.png' %}">

    {% block extra_head %}{% endblock %}
</head>

<body>

<div id="fb-root"></div>
<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="{% url 'core:home' %}">{% trans 'XSD' %}</a>

            <div class="nav-collapse collapse">
                <ul class="nav">
                    <li id="home"><a href="{% url 'core:home' %}">{% trans 'Home' %}</a></li>
                    <li id="blog"><a href="{% url 'blog:list' %}">{% trans 'Blog' %}</a></li>
                    <li><a href="#about">{% trans 'Sobre' %}</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">{% trans 'Serviços' %} <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">{% trans 'Sites' %}</a></li>
                            <li><a href="#">{% trans 'Aplicativos' %}</a></li>
                            <li><a href="#">{% trans 'Ícones' %}</a></li>
                            <li><a href="#">{% trans 'Identidade' %}</a></li>
                            <li class="divider"></li>
                            <li class="nav-header">{% trans 'Categorias' %}</li>
                            <li><a href="#">{% trans 'Criação' %}</a></li>
                            <li><a href="#">{% trans 'Desenvolvimento' %}</a></li>
                        </ul>
                    </li>
                    <li><a href="#portfolio">{% trans 'Portfólio' %}</a></li>
                    <li id="contact"><a href="{% url 'core:contact' %}">{% trans 'Contato' %}</a></li>
                </ul>
                <form class="navbar-search pull-left" action="">
                    <input type="text" class="search-query span2" placeholder="{% trans 'Pesquisar' %}">
                </form>
                <ul class="nav pull-right">

                    {% if user.is_authenticated %}
                    <li><a href="{% url 'core:logout' %}">{% trans 'Sair' %}</a></li>
                    <li class="divider-vertical"></li>
                    <li class="dropdown">

                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            {% if user.first_name and user.last_name %}
                                {{ user.first_name }} {{ user.last_name }}
                            {% elif user.first_name %}
                                {{ user.first_name }}
                            {% else %}
                                {{ user.username }}
                            {% endif %}
                            <b class="caret"></b>
                        </a>

                        <ul class="dropdown-menu">
                            <li id="profile_detail"><a href="{{ user.get_profile.get_absolute_url }}">{% trans 'Perfil' %}</a></li>
                            <li class="register"><a href="{% url 'core:register_update' %}">{% trans 'Editar' %}</a></li>
                            <li class="divider"></li>
                            <li id="password_change"><a href="{% url 'core:password_change' %}">{% trans 'Alterar senha' %}</a></li>
                        </ul>
                    </li>
                    {% else %}
                        <li class="register"><a href="{% url 'core:register' %}">{% trans 'Cadastro' %}</a></li>
                        <li class="divider-vertical"></li>
                        <li id="login"><a href="{% url 'core:login' %}">{% trans 'login' %}</a></li>
                    {% endif %}

                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
    </div>
</div>

<div class="container">
    {% include 'snippets/message.html' %}
    {% block content %}
        <div class="row">
            <div class="span8">
                <h3 class="page-header">{% trans 'Aguarde!' %}</h3>
                <p>{% trans 'Para mais informações entre em contato por' %} <a href="{% url 'core:contact' %}">email</a>.</p>
            </div>
            <div class="span4">
                {% include "blog/blogroll.html" %}
            </div>
        </div>
    {% endblock %}
</div>
<!-- /container -->

<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="span3">
                <h4 class="brand-footer"><a class="brand" href="{% url 'core:home' %}">{% trans 'XSD' %}</a></h4>
                <p class="brand-slogan">Extreme Software & Design</p>
            </div>
            <div class="span2">
                <ul>
                    <li><h4>{% trans 'Site' %}</h4></li>
                    <li><a href="{% url 'core:home' %}">{% trans 'Home' %}</a></li>
                    <li><a href="{% url 'blog:list' %}">{% trans 'Blog' %}</a></li>
                    <li><a href="#about">{% trans 'Sobre' %}</a></li>
                    <li><a href="#portfolio">{% trans 'Portfólio' %}</a></li>
                    <li><a href="{% url 'core:contact' %}">{% trans 'Contato' %}</a></li>
                </ul>
            </div>
            <div class="span2">
                <ul>
                    <li><h4>{% trans 'Serviços' %}</h4></li>
                    <li><a href="#">{% trans 'Sites' %}</a></li>
                    <li><a href="#">{% trans 'Aplicativos' %}</a></li>
                    <li><a href="#">{% trans 'Ícones' %}</a></li>
                    <li><a href="#">{% trans 'Identidade' %}</a></li>
                </ul>
            </div>
            <div class="span2">
                <ul>
                    <li><h4>{% trans 'Categorias' %}</h4></li>
                    <li><a href="#">{% trans 'Criação' %}</a></li>
                    <li><a href="#">{% trans 'Desenvolvimento' %}</a></li>
                </ul>
            </div>
            {% include "snippets/social.html" %}
        </div>
    </div>
</footer>
<!-- /footer -->

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap-transition.js' %}"></script>
<script src="{% static 'js/bootstrap-alert.js' %}"></script>
<script src="{% static 'js/bootstrap-modal.js' %}"></script>
<script src="{% static 'js/bootstrap-dropdown.js' %}"></script>
<script src="{% static 'js/bootstrap-scrollspy.js' %}"></script>
<script src="{% static 'js/bootstrap-tab.js' %}"></script>
<script src="{% static 'js/bootstrap-tooltip.js' %}"></script>
<script src="{% static 'js/bootstrap-popover.js' %}"></script>
<script src="{% static 'js/bootstrap-button.js' %}"></script>
<script src="{% static 'js/bootstrap-collapse.js' %}"></script>
<script src="{% static 'js/bootstrap-carousel.js' %}"></script>
<script src="{% static 'js/bootstrap-typeahead.js' %}"></script>
<script src="{% static 'js/application.js' %}"></script>
{% block script %}<script>$("#home").addClass("active")</script>{% endblock %}

<script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-12922546-1']);
    _gaq.push(['_trackPageview']);

    (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

</script>
<!-- /analytics -->

</body>
</html>